addSbtPlugin("org.scala-native"   % "sbt-scala-native"         % "0.5.5")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.17.0")
addSbtPlugin("org.portable-scala" % "sbt-crossproject"                % "1.3.2")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"        % "1.3.2")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject"   % "1.3.2")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.5.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.12.1")
